TEAM_CHAOS = 1
TEAM_CLASSD = 2
TEAM_SCIENTIFICDEPARTMENT = 3
TEAM_SECURITYDEPARTMENT = 4
TEAM_MOBILETASKFORCE = 5
TEAM_RAPIDRESPONSETEAM = 6
TEAM_INTELLIGENCEAGENCY = 7
TEAM_SITEDIRECTOR = 8
TEAM_O5COMMAND = 9
TEAM_SCP = 10

DEFAULT_WALKSPEED = 100
DEFAULT_RUNSPEED = 160

TEAM_SHORT_NAMES = {
    [0] = "Connecting",
    [1001] = "Unassigned",
    [1002] = "Spectator",
    [TEAM_CHAOS] = "Chaos",
    [TEAM_CLASSD] = "CD",
    [TEAM_SCIENTIFICDEPARTMENT] = "ScD",
    [TEAM_SECURITYDEPARTMENT] = "SD",
    [TEAM_MOBILETASKFORCE] = "MTF",
    [TEAM_RAPIDRESPONSETEAM] = "RRT",
    [TEAM_INTELLIGENCEAGENCY] = "IA",
    [TEAM_SITEDIRECTOR] = "SiD",
    [TEAM_O5COMMAND] = "O5",
    [TEAM_SCP] = "SCP"
}